SimpleStore partially revert 8fed42808046192e33c4f177db6315005286c9e0 that breaks vagrant setup
old versions of Gio.Monitor do not support all the same signal names leading to this trace:
INFO:eos_data_distribution.ndn.base:Register prefix: /endlessm/subscriptions/installed
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/cProfile.py", line 199, in <module>
    main()
  File "/usr/lib/python2.7/cProfile.py", line 192, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/usr/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "/vagrant/eos_data_distribution/store/ostree_store.py", line 54, in <module>
    main()
  File "/vagrant/eos_data_distribution/store/ostree_store.py", line 49, in main
    base=args.store_dir, prefix=SUBSCRIPTIONS_SOMA)
  File "eos_data_distribution/SimpleStore/__init__.py", line 43, in __init__
    self.publish_all_names(base)
  File "eos_data_distribution/SimpleStore/__init__.py", line 86, in publish_all_names
    for s in ['created', 'moved-in', 'renamed']]
TypeError: <Monitor object at 0x7f5e2d0608c0 (eos_data_distribution+DirTools+Monitor at 0xb40220)>: unknown signal name: moved-in

Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>